project_id = "jehgwsthqsltndybqoce"

[functions.generate-story-script]
verify_jwt = true

[functions.generate-avatar]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.generate-character]
verify_jwt = true

[functions.generate-voice-dialogue]
verify_jwt = true